language: objective-c
osx_image: xcode8
xcode_workspace: Example/Puree.xcworkspace
xcode_scheme: PureeTests
before_install:
  - gem update cocoapods --pre # Install 1.1.0.rc.2
podfile: Example/Podfile
